name: CI Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  code-change:
    name: Skip Checks?
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '[
            "docs/**",
            ".github/**",
            ".resources/**",
            "logos/**",
            "README.md",
            "CHANGELOG.md",
            "CONTRIBUTING.md",
            ".pre-commit-config.yaml",
            ".readthedocs.yaml",
            "pyproject.toml"
            ]'
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

  lint:
    name: ðŸ§º Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run lint tests
        uses: ./.github/actions/lint

  unit-tests:
    name: ðŸ§ª Tests
    needs: code-change
    if: ${{ needs.code-change.outputs.should_skip != 'true'}}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest"]
        python-version: ["3.9", "3.13"] # oldest and latest
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run unit tests
        uses: ./.github/actions/test
  all-green:
    name: âœ… All Green
    if: always()
    needs:
      - lint
      - unit-tests
    runs-on: Ubuntu-latest

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: unit-tests
          jobs: ${{ toJSON(needs) }}
